nome = input("Qual é seu nome?\n")
print("Prazer em te conhecer {:20}!".format(nome))
print("Prazer em te conhecer {:>20}!".format(nome))
print("Prazer em te conhecer {:<20}!".format(nome))
print("Prazer em te conhecer {:^20}!".format(nome))
print("Prazer em te conhecer {:=^20}!".format(nome))