a = input('Digite algo: ')
print('O tipo é {}\n'.format(type(a)))
print('Só tem espaços? {}\n'.format(a.isspace()))
print('É um número? {}\n'.format(a.isnumeric()))
print('É letra do alfabéto? {}\n'.format(a.isalpha()))
print('É  alfanumério? {}\n'.format(a.isalnum()))
print('Está em minúsculas? {}\n'.format(a.islower()))
print('Está em maiúsculas? {}\n'.format(a.isupper()))
print('Está em capitalizada? {}\n'.format(a.istitle()))
